CL\Slack\Model\UserProfile:
    properties:
        image34:
            type: string
            serialized_name: image_34
        image44:
            type: string
            serialized_name: image_44
        image68:
            type: string
            serialized_name: image_68
        image88:
            type: string
            serialized_name: image_88
        image102:
            type: string
            serialized_name: image_102
        image132:
            type: string
            serialized_name: image_132
        image_default:
            type: string
